kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: default
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match   *
        region eu-central-1
        log_group_name fluent-bit-cloudwatch
        log_stream_prefix from-fluent-bit-
        auto_create_group true