apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-eks
spec:
  interval: 10m
  url: https://aws.github.io/eks-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: aws-eks-charts
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/aws/eks-charts