apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/kubernetes-sigs/metrics-server