apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1m0s
  path: ./manifests/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: metrics-server
    namespace: flux-system
  validation: client