---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: env/dev
  secretRef:
    name: flux-system
  url: ssh://git@github.com/lreimer/hands-on-flux2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/flux2-dev-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
