apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: jakartaee8-java11
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/lreimer/jakartaee8-java11